name       : t1utils
version    : '1.42'
release    : 1
source     :
    - https://github.com/kohler/t1utils/archive/refs/tags/v1.42.tar.gz : d385fa78fca179e5edcf962bf1545a926f365c03e62b5a0ca5d80f104727ce81
license    : MIT
component  : multimedia.graphics
summary    : Utilities for manupulating Adobe Type 1 font software
description: |
    T1utils is a collection of simple programs for manipulating PostScript Type 1 fonts. Together, they allow you to convert between PFA (ASCII) and PFB (binary) formats, disassemble PFA or PFB files into human-readable form, and reassemble them into PFA or PFB format. Additionally you can extract font resources from a Macintosh font file or create a Macintosh Type 1 font file from a PFA or PFB font.
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
